name: instagram_clone
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5     # My state management #
  flutter: 
    sdk: flutter
  flutter_screenutil: ^5.5.4          #used for responsive design
  get_storage: ^2.0.3                 #used for storage
  dio: ^4.0.6                         #used EVERY WHERE
  font_awesome_flutter: ^10.2.1     
  infinite_scroll_pagination: ^3.2.0  #used EVERY WHERE
  
  carousel_slider: ^4.1.1          #used in post
  smooth_page_indicator: ^1.0.0+2  #used in post
  video_player: ^2.4.7             #used in post/story
  image_picker: ^0.8.6             #used in add post/story
  flutter_bounce: ^1.1.0
  flutter_launcher_icons: ^0.10.0
  mask_text_input_formatter: ^2.4.0 #used in signup
  holding_gesture: ^1.1.0           
  pausable_timer: ^1.0.0+6          #used in story
  cube_transition: ^1.0.2
  flutter_carousel_slider: ^1.0.9   #used in story

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/


flutter_icons:
  android: true
  # background_color: "#ffffff"
  image_path_android: assets/icons/instagram_app_icon.png

